# Generated by Django 3.0.7 on 2020-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200623_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
