# Generated by Django 3.0.7 on 2020-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200624_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('shipped', 'SHIPPED'), ('deliver', 'DELIVER')], default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
